### ISSUE TITLE
v1.12.2 isn't available on dockerhub

### ISSUE THREAD

**Issue by ianwinter** [henrywhitaker3/Speedtest-Tracker#1018]
Please can v1.12.2 be pushed to Docker!

**Comment by ianwinter** [comment]
Never mind, I built it using this (adding to portainer):

```
version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker:dev
        ports:
            - 8765:80
        volumes:
            - /srv/dev-disk-by-uuid-x-x-x-x/config/speedtest:/config
        environment:
            - TZ=
            - PGID=
            - PUID=
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped

```
