### ISSUE TITLE
[BUG] Failed to resolve host name. Cancelling test suite. - speedtest cli defect?

### ISSUE THREAD

**Issue by Kofl** [henrywhitaker3/Speedtest-Tracker#1053]
**Describe the bug**
Failed to resolve host name. Cancelling test suite.

**To Reproduce**
default docker-compose image, when running the speedtest

```
version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker
        ports:
            - 8765:80
        volumes:
            - /root/docker/speedtest/config:/config
        environment:
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped
```

**Expected behavior**
speedtest result

**Context**
 - OS: current docker version, latest image

**Additional context**
name resolution and web access via wget is fine, tested via 

`docker-compose exec speedtest bash`

Running directly
` /config/www/app/Bin/speedtest`
outputs the same error:
_[error] Server Selection - Failed to find a working test server. (NoServers)_
