### ISSUE TITLE
[BUG] wrong datetime 

### ISSUE THREAD

**Issue by xinmans** [henrywhitaker3/Speedtest-Tracker#1087]

**Comment by shakasan** [comment]
As the description of the issue is full of details ^^, I guess it's the same issue as I'm facing as well.

Here a screenshot of Graphs, All tests section and the corresponding docker-compose config file.

We can see in All tests sections, that Month/Day are permuted from time to time, thus leading to wrongly displayed internet connection issue on the graphs.

```
version: '3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker
        ports:
            - 8765:80
        volumes:
            - ./config:/config
        environment:
            - TZ=Europe/BRUSSELS
            - PGID=100
            - PUID=1000
            - OOKLA_EULA_GDPR=true  # Paramètre obligatoire à 'true' pour accepter les conditions d'utilisation des services Ookla. Si ce paramètre n'est pas renseigné, le conteneur ne démarrera pas.
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped
```

![all_tests_example](https://user-images.githubusercontent.com/16532111/205387985-3c1d8449-e3f4-420b-8f3f-978758ffc121.png)
![graphs_example](https://user-images.githubusercontent.com/16532111/205387995-05f93d64-3981-4e40-afdb-9a0923721613.png)

**Comment by shakasan** [comment]
As the description of the issue is full of details ^^, I guess it's the same issue as I'm facing as well.

Here are screenshot of Graphs/All tests section and the corresponding docker-compose config file.

We can see in All tests sections, that Month/Day are permuted from time to time, thus leading to wrongly displayed internet connection issue on the graphs.

I already re-created the stack from scratch just in case, but the issue is still there.

The command `date` within the container return the right date/time `Fri Dec  2 22:32:04 CET 2022`.

```
version: '3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker
        ports:
            - 8765:80
        volumes:
            - ./config:/config
        environment:
            - TZ=Europe/Brussels
            - PGID=100
            - PUID=1000
            - OOKLA_EULA_GDPR=true  # Paramètre obligatoire à 'true' pour accepter les conditions d'utilisation des services Ookla. Si ce paramètre n'est pas renseigné, le conteneur ne démarrera pas.
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped
```
![all_tests_example](https://user-images.githubusercontent.com/16532111/205391308-53fb3c5d-5c0b-45c4-b121-c2f6644f75ea.png)
![graphs_example](https://user-images.githubusercontent.com/16532111/205391326-e8711377-63f0-465e-8e50-fbd43a3c4cd8.png)
