### ISSUE TITLE
[BUG] Speedtest is not working because speedtest-cli requires accepting the license before use

### ISSUE THREAD

**Issue by rostfirsikov** [henrywhitaker3/Speedtest-Tracker#1130]
**Describe the bug**
The freshly installed speedtest-tracker is not working because fresh ookla speedtest-cli requires accepting the license before use.

I kindly request the developers to add some automation to this process.

**Context**
 - OS: Docker, Ubuntu
 - Speedtest Tracker Version: 1.12.0

**Additional context**
```yaml
docker-compose.yml:
version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker
        ports:
            - 8008:80
        volumes:
            - ./config:/config
        environment:
            - TZ=Europe/Kiev
            - PGID=1000
            - PUID=1000
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped
```

/config/log/queue.log:
```log
[2023-08-08 13:32:54][1] Processing: App\Jobs\SpeedtestJob
[2023-08-08 13:33:03][1] Failed:     App\Jobs\SpeedtestJob
```

container log with problem:
```
==============================================================================
You may only use this Speedtest software and information generated
from it for personal, non-commercial use, through a command line
interface on a personal computer. Your use of this software is subject
to the End User License Agreement, Terms of Use and Privacy Policy at
these URLs:
	https://www.speedtest.net/about/eula
	https://www.speedtest.net/about/terms
	https://www.speedtest.net/about/privacy
==============================================================================
To accept the message please run speedtest interactively or use the following: 
    speedtest --accept-license

```

**Comment by rostfirsikov** [comment]
I solved my problem the hard way.

I entered the container.
```bash
docker exec -it speedtest bash 
```
Edited `/etc/passwd` with `nano`.
Changed the shell to `bash` for user `abc`.
Executed the command:
```bash
su - abc -c '/config/www/app/Bin/speedtest'
```
And accepted the license agreement.

But this approach is not for beginners. Something needs to be changed!

**Comment by mouledla** [comment]
Same bug here, I used your workaround, @rostfirsikov and it worked. Thanks!

**Comment by theBissonBison** [comment]
For future souls who happen across this issue thread, I made a new image that fixed this problem - here is the docker compose:

```
version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: kylebisson01/speedtest:nonroot
        ports:
            - 8765:80
        volumes:
            - [config location]:/config
        environment:
            - TZ=[Timezone e.g. America/New_York]
            - PGID=1000
            - PUID=1000
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: always
```
