### ISSUE TITLE
[Support question] graphics statistic history always empte

### ISSUE THREAD

**Issue by IIIdefconIII** [henrywhitaker3/Speedtest-Tracker#1153]
Can someone help me out out to help me telling me how to get the table crharts?
![image](https://github.com/user-attachments/assets/96fb38e6-3605-45b5-8b1d-738a6aebf96f)

**Comment by IIIdefconIII** [comment]
```
# Speedtest Tracker____________________
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 8765:80
    environment:
      PUID: $PUID
      PGID: $PGID
      UMASK: $UMASK
      TZ: $TZ
      OOKLA_EULA_GDPR: "true"
    volumes:
      - $DOCKERDIR/speedtest:/config
    logging:
       driver: "json-file"
       options:
         max-file: "10"
         max-size: "200k"
```
