### ISSUE TITLE
When BASE_PATH is set, the app never loads [BUG]

### ISSUE THREAD

**Issue by lmarianski** [henrywhitaker3/Speedtest-Tracker#207]
**Describe the bug**
When BASE_PATH is set, the app never loads.

**To Reproduce**
Steps to reproduce the behaviour:
1. docker-compose.yml
```yaml
version: "3.2"
services:
  speedtest:
    image: henrywhitaker3/speedtest-tracker
    container_name: speedtest
    ports:
      - 8765:80
    volumes: 
      - ./speedtest:/config
    environment:
      - TZ=Europe/Warsaw
      - PUID=1000
      - PGID=1000
      - OOKLA_EULA_GDPR=true
      - BASE_PATH=/speedtest      
    restart: unless-stopped
```
2. Open `http://localhost:8765/speedtest`
3. Watch loading screen forever

**Expected behaviour**
The app to load

**Context**
 - OS: Docker
 - Speedtest-Tracker Version: latest `henrywhitaker3/speedtest-tracker` image
