### ISSUE TITLE
Error: [11] Cannot read: Resource temporarily unavailable","level":"error"}

### ISSUE THREAD

**Issue by Rustymage** [henrywhitaker3/Speedtest-Tracker#408]
I'm having some issues with the speed tests ceasing at some point after the docker container is spun up. Seemingly randomly. A restart fixes sometimes.

Here is my docker command:

```
version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker:dev
        ports:
            - 8765:80
        volumes:
            - ./data:/config
        environment:
            - TZ=EUROPE/LONDON
            - PGID=1000
            - PUID=1000
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped
```

Here are my errors.

```
{"type":"log","timestamp":"2020-12-09T21:00:10Z","message":"Error: [11] Cannot read from socket: Resource temporarily unavailable","level":"error"}


{"type":"log","timestamp":"2020-12-09T23:00:06Z","message":"Error: [110] Cannot open socket: Timeout occurred in connect.","level":"error"}


{"type":"log","timestamp":"2020-12-10T01:00:13Z","message":"Error: [11] Cannot read: Resource temporarily unavailable","level":"error"}
```

I wonder if it is linked to https://github.com/henrywhitaker3/Speedtest-Tracker/issues/148

Any thoughts or help?

Thanks.
