### ISSUE TITLE
[BUG] Fails to find a working test server

### ISSUE THREAD

**Issue by 7opf** [henrywhitaker3/Speedtest-Tracker#433]
**Describe the bug**
Tests fail due to speedtest not finding any working servers to test

**To Reproduce**

`docker-compose up`

```
version: '3.3'
services:
  speedtest:
    restart: always
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    ports:
      - 8765:80
    volumes:
      - /volume1/docker/speedtest/data:/config
    environment:
      - TZ=Europe/Zurich # Also tried "CET" and omitting this env var entirely as it was undocumented
      - PGID=<GID>
      - PUID=<UID>
      - AUTH=true
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
```

**Expected behavior**
tests run successfully

**Logs**
```
speedtest    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
speedtest    | [s6-init] ensuring user provided files have correct perms...exited 0.
speedtest    | [fix-attrs.d] applying ownership & permissions fixes...
speedtest    | [fix-attrs.d] done.
speedtest    | [cont-init.d] executing container initialization scripts...
speedtest    | [cont-init.d] 01-envfile: executing...
speedtest    | [cont-init.d] 01-envfile: exited 0.
speedtest    | [cont-init.d] 10-adduser: executing...
speedtest    | usermod: no changes
speedtest    |
speedtest    | -------------------------------------
speedtest    |           _         ()
speedtest    |          | |  ___   _    __
speedtest    |          | | / __| | |  /  \
speedtest    |          | | \__ \ | | | () |
speedtest    |          |_| |___/ |_|  \__/
speedtest    |
speedtest    |
speedtest    | Brought to you by linuxserver.io
speedtest    | -------------------------------------
speedtest    |
speedtest    | To support LSIO projects visit:
speedtest    | https://www.linuxserver.io/donate/
speedtest    | -------------------------------------
speedtest    | GID/UID
speedtest    | -------------------------------------
speedtest    |
speedtest    | User uid:    1026
speedtest    | User gid:    100
speedtest    | -------------------------------------
speedtest    |
speedtest    | [cont-init.d] 10-adduser: exited 0.
speedtest    | [cont-init.d] 20-config: executing...
speedtest    | [cont-init.d] 20-config: exited 0.
speedtest    | [cont-init.d] 30-keygen: executing...
speedtest    | using keys found in /config/keys
speedtest    | [cont-init.d] 30-keygen: exited 0.
speedtest    | [cont-init.d] 40-config: executing...
speedtest    | GeoIP2 database found
speedtest    | [cont-init.d] 40-config: exited 0.
speedtest    | [cont-init.d] 50-speedtest: executing...
speedtest    | [error] Server Selection - Failed to find a working test server. (NoServers)
```

**Context**
 - OS: Docker, Synology DSM 7 (preview)
 - Speedtest-Tracker Version: latest
