### ISSUE TITLE
[BUG] - Auth is not working 

### ISSUE THREAD

**Issue by ansred** [henrywhitaker3/Speedtest-Tracker#547]
**Describe the bug**
I added the environment Auth=true, and it's not active

**To Reproduce**
I used the following compose file

```
version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker
        ports:
            - 8766:80
        volumes:
            - /volume1/docker/Speedtest-Tracker/config:/config
        environment:
            - TZ=America/Toronto
            - PGID=1029
            - PUID=100
            - OOKLA_EULA_GDPR=true
            - Auth=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped
```

**Expected behavior**
To see login page to authenticate 

Field	Function
username	admin@admin.com
password	password

**Context**
 - OS: Docker - Synology DSM NAS - Portainer
 - Speedtest-Tracker Version: Latest - v1.10.4

**Additional context**
Is there another place in the config files I can edit manually to enable authentication?

![image](https://user-images.githubusercontent.com/5244872/113050328-b3933380-9172-11eb-83e9-ffb42953a822.png)

Thanks
