### ISSUE TITLE
[BUG] Machine does not boot on arm

### ISSUE THREAD

**Issue by brunogama** [henrywhitaker3/Speedtest-Tracker#553]
Followed the instructions on README.md but nothing seens to work. The logs say is is trying to make a cert key and fail.

**To Reproduce**
`docker-compose -up d`

**Compose file**
```
---
version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker:latest-arm
        restart: always
        volumes:
            - ./config:/config:rw
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Sao_Paulo
          - OOKLA_EULA_GDPR=true
          - AUTH=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        ports:
          - '8765:80'
```

**Expected behavior**
Use the app

**Log**
[_speedtest_logs.txt](https://github.com/henrywhitaker3/Speedtest-Tracker/files/6256012/_speedtest_logs.txt)

**Context**
 - OS: Raspberry OS Lite - RPI 4 4gb- Docker
 - Speedtest-Tracker Version: latestar-arm
