### ISSUE TITLE
Copying site files each time is inefficient

### ISSUE THREAD

**Issue by agneevX** [henrywhitaker3/Speedtest-Tracker#641]
Hello.

I'm running Speedtest-tracker on my Raspberry Pi, which has a SD card. 

When the container is started, it copies tens of thousands of files to the mapped config folder (`www`).

This causes the server to severely freeze and system load to balloon to over `12`.

Not only that, heavy I/O of this kind also causes issues with the SD card.

**Context**
 - OS: Ubuntu 20.04
 - Speedtest-Tracker Version: 1.10.4

**Comment by agneevX** [comment]
Resorted to storing the data in-memory

```yml
speedtest-tracker:
  container_name: speedtest-tracker
  image: henrywhitaker3/speedtest-tracker:latest-arm
  restart: unless-stopped
  ports:
    - 8700:80
  healthcheck:
    test: ["CMD", "curl", "localhost", "-fso", "/dev/null"]
  environment:
    - PUID=1001
    - PGID=1001
    - UMASK=002
    - TZ=
    - OOKLA_EULA_GDPR=true
  volumes:
    - /opt/appdata/speedtest-tracker:/config
    - type: tmpfs
      target: /config/log
      tmpfs:
        size: 32mb
    - type: tmpfs
      target: /config/www/node_modules
      tmpfs:
        size: 400mb
    - type: tmpfs
      target: /config/www/vendor
      tmpfs:
        size: 100mb
    - type: tmpfs
      target: /config/www/public
      tmpfs:
        size: 50mb
```
