### ISSUE TITLE
[BUG] jailing process inside rootfs caused: invalid argument: unknown

### ISSUE THREAD

**Issue by MrCaringi** [henrywhitaker3/Speedtest-Tracker#648]
**Describe the bug**
The container doesnt start

**To Reproduce**
1. just run `docker-compose up -d` 

**Expected behavior**
To get propperly started

**Screenshots**
```
jfc@NOSTROMO:/volume1/home/jfc/script/dc-general $ docker-compose up -d && docker logs -f speedtest
Pulling speedtest (henrywhitaker3/speedtest-tracker:)...
latest: Pulling from henrywhitaker3/speedtest-tracker
c91af5d1b23e: Pull complete
740fcfa9e15a: Pull complete
ce5b3694a6d6: Pull complete
a83d676a55d9: Pull complete
38ac933c5d8d: Pull complete
dc32e0469fc9: Pull complete
2692dc6e8a90: Pull complete
36a44203a304: Pull complete
df68ab8ba510: Pull complete
712e86a465e0: Pull complete
d3bce8b43a04: Pull complete
Digest: sha256:125c03f57495452b22713dc1482f40fa89b7ee67ccfa81f7409caeabccc95a93
Status: Downloaded newer image for henrywhitaker3/speedtest-tracker:latest
watchtower is up-to-date
portainer is up-to-date
syncthing is up-to-date
netdata is up-to-date
Creating speedtest ... error

ERROR: for speedtest  Cannot start service speedtest: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:117: jailing process inside rootfs caused: invalid argument: unknown

ERROR: for speedtest  Cannot start service speedtest: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:117: jailing process inside rootfs caused: invalid argument: unknown
ERROR: Encountered errors while bringing up the project.
```
**docker-compose.yml**
```
# another services before this line
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker
        hostname: NOSTROMO
        labels:
            com.centurylinklabs.watchtower.enable: "true"
        ports:
            - 8504:80
        volumes:
            - /volume4/hdd_cache/speedtest2:/config
        environment:
            - TZ=America/Monterrey
            - PGID=1000
            - PUID=100
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "100"
                max-size: "2000k"
        restart: unless-stopped
```

**Context**
 - OS: Linux ASUSTOR NAS 4.14.x #1 SMP Mon May 10 00:30:33 CST 2021 x86_64 GNU/Linux
 - Speedtest-Tracker Version: lastest

**Additional context**
Included in the same docker-compose.yml among other services: watchtower, portainer, syncthing, netdata
docker-compose file format: 2.4
