### ISSUE TITLE
[BUG] TimeZone not working

### ISSUE THREAD

**Issue by Aerya** [henrywhitaker3/Speedtest-Tracker#661]
Hi,

**Describe the bug**
I use the Docker version (:lastest) with TZ env (Europe/Paris) but it still reports as UTC.
php.ini is correct
![](https://i.imgur.com/0saUDL3.png)

**To Reproduce**
```
version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker
        ports:
            - 8765:80
        volumes:
            - /volume1/docker/speedtest-tracker/:/config
        environment:
            - TZ=Europe/Paris
            - PGID=100
            - PUID=1024
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped
```

**Screenshots**
![](https://i.imgur.com/LzrznjI.png)

**Context**
 - OS: Synology DSM7
 - Speedtest-Tracker Version: 1.10.4
