### ISSUE TITLE
can't make it working on rpi4 anymore 

### ISSUE THREAD

**Issue by rubenixnagios** [henrywhitaker3/Speedtest-Tracker#677]
Hello,

Running my little home server with a rpi4 (8GB version) with debian buster 10 32bit.
Previously had v1.10.4 working until server got an hdd failure and had to restore all my containers.

I deployed following container:

### Compose file

```
version: '3.3'
services:
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker:latest-arm
    ports:
      - 8765:80
    volumes:
      - /XXX/:/config
    environment:
      - TZ=Europe/Andorra
      - PGID=1000
      - PUID=1000
      - OOKLA_EULA_GDPR=true
      - SLACK_WEBHOOK=xxx
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
```

Web UI working and reading metrics from database but cannot perform a successful test on v1.12.0 (with or without a server on the config)
(same result deploying with latest tag)
Accepted EULA on the container itself seems to work but cannot perform a test as it asks again for accept the message...

### inside container:

root@6e9cf651d641:/# php /config/www/artisan speedtest:run
Running speedtest, this might take a while...

Ookla collects certain data through Speedtest that may be considered
personally identifiable, such as your IP address, unique device
identifiers or location. Ookla believes it has a legitimate interest
to share this data with internet providers, hardware manufacturers and
industry regulators to help them understand and create a better and
faster internet. For further information including how the data may be
shared, where the data may be transferred and Ookla's contact details,
please see our Privacy Policy at:

       http://www.speedtest.net/privacy

To accept the message please run speedtest interactively or use the following:

    speedtest --accept-gdpr
Something went wrong running the speedtest.
root@6e9cf651d641:/# php /config/www/artisan speedtest:eula
Acceping EULA
root@6e9cf651d641:/# php /config/www/artisan speedtest:run
Running speedtest, this might take a while...

Ookla collects certain data through Speedtest that may be considered
personally identifiable, such as your IP address, unique device
identifiers or location. Ookla believes it has a legitimate interest
to share this data with internet providers, hardware manufacturers and
industry regulators to help them understand and create a better and
faster internet. For further information including how the data may be
shared, where the data may be transferred and Ookla's contact details,
please see our Privacy Policy at:

       http://www.speedtest.net/privacy

To accept the message please run speedtest interactively or use the following:

    speedtest --accept-gdpr
Something went wrong running the speedtest.

Any change to revert back to 1.10.4 anyhow?
