### ISSUE TITLE
[BUG] Error starting latest-arm version on RaspBerry Pi4 with 64 bit OS Raspberry

### ISSUE THREAD

**Issue by paolonervi** [henrywhitaker3/Speedtest-Tracker#678]
**Describe the bug**
The docker container does not start.
I receive the following error:
`4153394064:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:`

**To Reproduce**

1. Create a directory `speedtest `

2. Create inside the `speedtest` directory a `docker-compose-yml` file with the following info:

```
version: '2'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker:latest-arm
        ports:
            - 8765:80
        volumes:
            - /home/pi/speedtest/config:/config
        environment:
            - TZ=Italy/Turin
            - PGID=0
            - PUID=0
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped

```
2. Run the following command: `docker-compose up`
3. You'll see the following info:
```
pi@pi-w-100:~/speedtest $ docker-compose up
Creating network "speedtest_default" with the default driver
Creating speedtest ... done
Attaching to speedtest
speedtest    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
speedtest    | [s6-init] ensuring user provided files have correct perms...exited 0.
speedtest    | [fix-attrs.d] applying ownership & permissions fixes...
speedtest    | [fix-attrs.d] done.
speedtest    | [cont-init.d] executing container initialization scripts...
speedtest    | [cont-init.d] 01-envfile: executing... 
speedtest    | [cont-init.d] 01-envfile: exited 0.
speedtest    | [cont-init.d] 10-adduser: executing... 
speedtest    | 
speedtest    | -------------------------------------
speedtest    |           _         ()
speedtest    |          | |  ___   _    __
speedtest    |          | | / __| | |  /  \ 
speedtest    |          | | \__ \ | | | () |
speedtest    |          |_| |___/ |_|  \__/
speedtest    | 
speedtest    | 
speedtest    | Brought to you by linuxserver.io
speedtest    | -------------------------------------
speedtest    | 
speedtest    | To support LSIO projects visit:
speedtest    | https://www.linuxserver.io/donate/
speedtest    | -------------------------------------
speedtest    | GID/UID
speedtest    | -------------------------------------
speedtest    | 
speedtest    | User uid:    0
speedtest    | User gid:    0
speedtest    | -------------------------------------
speedtest    | 
speedtest    | [cont-init.d] 10-adduser: exited 0.
speedtest    | [cont-init.d] 20-config: executing... 
speedtest    | [cont-init.d] 20-config: exited 0.
speedtest    | [cont-init.d] 30-keygen: executing... 
speedtest    | generating self-signed keys in /config/keys, you can replace these with your own keys if required
speedtest    | Generating a RSA private key
speedtest    | .............+++++
speedtest    | ..........+++++
speedtest    | writing new private key to '/config/keys/cert.key'
speedtest    | -----
speedtest    | 4153394064:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
speedtest    | [cont-init.d] 30-keygen: exited 1.
speedtest    | [cont-finish.d] executing container finish scripts...
speedtest    | [cont-finish.d] done.
speedtest    | [s6-finish] waiting for services.
speedtest    | [s6-finish] sending all processes the TERM signal.
speedtest    | [s6-finish] sending all processes the KILL signal and exiting.
```

**Expected behavior**
I wish that the docker container could work also on a RPi4 without errors.

**Context**
 - OS: host: Raspberry Pi4 with OS Raspberry 64 bit.
 - Speedtest-Tracker Version: 

Thank you for your help.
Paul.
