### ISSUE TITLE
[Feature Request] Cull the node_modules folder in the docker image.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [henrywhitaker3/Speedtest-Tracker#744]
Are 22+k ( https://i.imgur.com/08Y7Eta.png ) files really necessary in the `www/node_modules` after I did a docker compose? Can't it be culled to include only the necessary parts for the app to work?

It's a PITA to back it up with Macrium Reflect.

packages.json says:

```
    "dependencies": {
        "@babel/plugin-proposal-class-properties": "^7.13.0",
        "chart.js": "^2.9.4",
        "csv-file-validator": "^1.10.1",
        "js-cookie": "^2.2.1",
        "react-beautiful-dnd": "^13.1.0",
        "react-bootstrap": "^1.5.1",
        "react-chartjs-2": "^2.11.1",
        "react-router": "^5.2.0",
        "react-router-dom": "^5.2.0",
        "react-toastify": "^7.0.3"
    }
```
yet the image is pulling 742 different modules with 22k+ files and putting them in the data folder.

This is the docker-compose.yml I use:
```
version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker
        ports:
            - 8765:80
        volumes:
            - /volume1/docker/speedtest:/config
        environment:
            - TZ=xxx
            #- PGID=
            #- PUID=
            - OOKLA_EULA_GDPR=true
        labels:
            - deunhealth.restart.on.unhealthy=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "1024k"
        restart: always
networks:
  default:
    name: dockernet
    external: true
```
