### ISSUE TITLE
HELP : Logging options, e.g. to csv

### ISSUE THREAD

**Issue by nodecentral** [henrywhitaker3/Speedtest-Tracker#944]
Hi,

i can see in the Docker compose there is the following logging option.
````
logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
````
Are there any other local options, e.g could I look to .csv ?
